@extends('layouts.app')
@section('title', 'Profilo aziendale · Commerciale AI')
@section('content')
<div class="toolbar"><div><h1>Profilo aziendale</h1><p class="muted">Completezza: <strong>{{ $settings->completeness ?? 0 }}%</strong>. L’AI usa solo informazioni dichiarate qui e nella knowledge base.</p></div><span class="badge">Onboarding</span></div>
<form class="card" method="post" action="{{ route('settings.organization.update') }}">@csrf @method('put')
<div class="grid grid-2"><div><label>Ragione sociale</label><input name="legal_name" value="{{ old('legal_name',$settings->legal_name) }}"></div><div><label>Nome commerciale *</label><input name="commercial_name" value="{{ old('commercial_name',$settings->commercial_name) }}" required></div><div><label>Settore *</label><input name="industry" value="{{ old('industry',$settings->industry) }}" required></div><div><label>Area geografica servita</label><input name="service_area" value="{{ old('service_area',$settings->service_area) }}"></div></div>
<label>Descrizione dell’attività *</label><textarea name="business_description" rows="4" required>{{ old('business_description',$settings->business_description) }}</textarea>
<label>Prodotti e servizi *</label><textarea name="products_services" rows="5" required>{{ old('products_services',$settings->products_services) }}</textarea>
<label>Cliente ideale *</label><textarea name="ideal_customer" rows="4" required>{{ old('ideal_customer',$settings->ideal_customer) }}</textarea>
<div class="grid grid-2"><div><label>Regole e fasce di prezzo</label><textarea name="pricing_rules" rows="5">{{ old('pricing_rules',$settings->pricing_rules) }}</textarea></div><div><label>Elementi distintivi</label><textarea name="differentiators" rows="5">{{ old('differentiators',$settings->differentiators) }}</textarea></div></div>
<div class="grid grid-2"><div><label>Domande di qualificazione, una per riga</label><textarea name="qualification_questions_text" rows="6">{{ old('qualification_questions_text',implode("\n",$settings->qualification_questions ?? [])) }}</textarea></div><div><label>Criteri di esclusione</label><textarea name="exclusion_criteria" rows="6">{{ old('exclusion_criteria',$settings->exclusion_criteria) }}</textarea></div></div>
<div class="grid grid-2"><div><label>Tono di voce *</label><input name="tone_of_voice" value="{{ old('tone_of_voice',$settings->tone_of_voice ?: 'professionale e diretto') }}" required></div><div><label>Tempo di risposta promesso (minuti)</label><input type="number" min="1" name="promised_response_minutes" value="{{ old('promised_response_minutes',$settings->promised_response_minutes) }}"></div><div><label>Mittente autorizzato</label><input type="email" name="authorized_sender" value="{{ old('authorized_sender',$settings->authorized_sender) }}"></div><div><label>Modalità appuntamento</label><input name="appointment_details" value="{{ old('appointment_details',$settings->appointment_details) }}"></div></div>
<label>Firma email *</label><textarea name="email_signature" rows="4" required>{{ old('email_signature',$settings->email_signature) }}</textarea>
@foreach($errors->all() as $error)<div class="error">{{ $error }}</div>@endforeach<br><button class="btn">Salva profilo</button></form>
@endsection
