@extends('layouts.app')
@section('title', 'Profilo aziendale · Daria')
@section('content')
<div class="toolbar"><div><h1>Profilo aziendale</h1><p class="muted">Completezza: <strong>{{ $settings->completeness ?? 0 }}%</strong>. L’AI usa solo informazioni dichiarate qui e nella knowledge base.</p></div><a class="btn" href="{{ route('setup-wizard.create') }}">Compila con Daria</a></div>
<div class="card" style="margin-bottom:1rem"><div class="toolbar" style="margin:0"><div><strong>Provider AI: {{ strtoupper($aiStatus['provider']) }}</strong><div class="muted">Modello {{ $aiStatus['model'] }} · la chiave è letta esclusivamente dal server</div></div><span class="badge {{ $aiStatus['configured'] ? '' : 'hot' }}">{{ $aiStatus['configured'] ? 'Configurato' : 'Chiave mancante' }}</span></div>@unless($aiStatus['configured'])<p class="error">Imposta <code>OPENAI_API_KEY</code> nel file <code>.env</code> del server per abilitare le analisi reali.</p>@endunless</div>
<form class="card" method="post" action="{{ route('settings.organization.update') }}">@csrf @method('put')
<div class="grid grid-2"><div><label>Ragione sociale</label><input name="legal_name" value="{{ old('legal_name',$settings->legal_name) }}"></div><div><label>Nome commerciale *</label><input name="commercial_name" value="{{ old('commercial_name',$settings->commercial_name) }}" required></div><div><label>Settore *</label><input name="industry" value="{{ old('industry',$settings->industry) }}" required></div><div><label>Area geografica servita</label><input name="service_area" value="{{ old('service_area',$settings->service_area) }}"></div></div>
<label>Descrizione dell’attività *</label><textarea name="business_description" rows="4" required>{{ old('business_description',$settings->business_description) }}</textarea>
<label>Prodotti e servizi *</label><textarea name="products_services" rows="5" required>{{ old('products_services',$settings->products_services) }}</textarea>
<label>Cliente ideale *</label><textarea name="ideal_customer" rows="4" required>{{ old('ideal_customer',$settings->ideal_customer) }}</textarea>
<div class="grid grid-2"><div><label>Regole e fasce di prezzo</label><textarea name="pricing_rules" rows="5">{{ old('pricing_rules',$settings->pricing_rules) }}</textarea></div><div><label>Elementi distintivi</label><textarea name="differentiators" rows="5">{{ old('differentiators',$settings->differentiators) }}</textarea></div></div>
<div class="grid grid-2"><div><label>Domande di qualificazione, una per riga</label><textarea name="qualification_questions_text" rows="6">{{ old('qualification_questions_text',implode("\n",$settings->qualification_questions ?? [])) }}</textarea></div><div><label>Criteri di esclusione</label><textarea name="exclusion_criteria" rows="6">{{ old('exclusion_criteria',$settings->exclusion_criteria) }}</textarea></div></div>
<div class="grid grid-2"><div><label>Tono di voce *</label><input name="tone_of_voice" value="{{ old('tone_of_voice',$settings->tone_of_voice ?: 'professionale e diretto') }}" required></div><div><label>Tempo di risposta promesso (minuti)</label><input type="number" min="1" name="promised_response_minutes" value="{{ old('promised_response_minutes',$settings->promised_response_minutes) }}"></div><div><label>Mittente autorizzato</label><input type="email" name="authorized_sender" value="{{ old('authorized_sender',$settings->authorized_sender) }}"></div><div><label>Modalità appuntamento</label><input name="appointment_details" value="{{ old('appointment_details',$settings->appointment_details) }}"></div></div>
<label>Firma email *</label><textarea name="email_signature" rows="4" required>{{ old('email_signature',$settings->email_signature) }}</textarea>
<hr style="margin:2rem 0;border:0;border-top:1px solid #e3e8ef">
<h2>Automazione conversazioni</h2>
<div class="warning">Funzione sperimentale. L’invio automatico avviene solo quando tutti i controlli deterministici sono superati. Mantieni attiva la modalità test interno durante il collaudo.</div>
@unless(config('commerciale-ai.automation.external_send_enabled'))<div class="notice">Il server accetta soltanto test interni. L’invio automatico verso clienti esterni è bloccato anche se viene disattivata la casella sottostante.</div>@endunless
<label style="font-weight:400"><input style="width:auto" type="checkbox" name="conversation_automation_enabled" value="1" @checked(old('conversation_automation_enabled',$settings->conversation_automation_enabled))> Abilita elaborazione automatica delle conversazioni</label>
<label style="font-weight:400"><input style="width:auto" type="checkbox" name="auto_analyze_new_leads" value="1" @checked(old('auto_analyze_new_leads',$settings->auto_analyze_new_leads))> Analizza automaticamente i nuovi lead</label>
<label style="font-weight:400"><input style="width:auto" type="checkbox" name="auto_send_initial_email" value="1" @checked(old('auto_send_initial_email',$settings->auto_send_initial_email))> Invia automaticamente la prima email</label>
<label style="font-weight:400"><input style="width:auto" type="checkbox" name="auto_send_quotes_enabled" value="1" @checked(old('auto_send_quotes_enabled',$settings->auto_send_quotes_enabled))> Consenti invio automatico dei preventivi affidabili</label>
<label style="font-weight:400"><input style="width:auto" type="checkbox" name="internal_test_only" value="1" @checked(old('internal_test_only',$settings->exists ? $settings->internal_test_only : true))> Limita l’automazione ai destinatari interni autorizzati</label>
<div class="grid grid-2"><div><label>Destinatari interni autorizzati, uno per riga</label><textarea name="automation_allowed_recipients_text" rows="4">{{ old('automation_allowed_recipients_text',implode("\n",$settings->automation_allowed_recipients ?? [])) }}</textarea></div><div><label>Massimo risposte automatiche per lead</label><input type="number" min="1" max="10" name="max_automatic_replies" value="{{ old('max_automatic_replies',$settings->max_automatic_replies ?? 3) }}"><label>Importo massimo automatico (€)</label><input type="number" min="0" step="0.01" name="max_auto_quote_amount" value="{{ old('max_auto_quote_amount',$settings->max_auto_quote_amount) }}"></div></div>
@foreach($errors->all() as $error)<div class="error">{{ $error }}</div>@endforeach<br><button class="btn">Salva profilo</button></form>

<section class="card" style="margin-top:1rem">
<h2>Listino strutturato</h2><p class="muted">Il prezzo viene sempre da queste regole; l’AI può soltanto spiegarlo.</p>
@foreach($pricingRules as $rule)
<form method="post" action="{{ route('settings.pricing-rules.update',$rule) }}" style="border-top:1px solid #e3e8ef;margin-top:1rem;padding-top:1rem">@csrf @method('put')
<div class="grid grid-2"><div><label>Nome</label><input name="name" value="{{ $rule->name }}" required></div><div><label>Parole chiave</label><input name="keywords_text" value="{{ implode(', ',$rule->keywords) }}" required></div><div><label>Prezzo minimo</label><input type="number" step="0.01" name="minimum_price" value="{{ $rule->minimum_price }}" required></div><div><label>Prezzo massimo</label><input type="number" step="0.01" name="maximum_price" value="{{ $rule->maximum_price }}" required></div></div>
<label>Campi obbligatori del payload, uno per riga</label><textarea name="required_fields_text" rows="2">{{ implode("\n",$rule->required_fields ?? []) }}</textarea><div class="grid grid-2"><div><label>Include</label><textarea name="includes" rows="3">{{ $rule->includes }}</textarea></div><div><label>Esclude</label><textarea name="excludes" rows="3">{{ $rule->excludes }}</textarea></div></div><label>Validità (giorni)</label><input type="number" name="validity_days" value="{{ $rule->validity_days }}" required><label style="font-weight:400"><input style="width:auto" type="checkbox" name="is_active" value="1" @checked($rule->is_active)> Attiva</label><br><button class="btn btn-muted">Aggiorna regola</button></form>
@endforeach
<form method="post" action="{{ route('settings.pricing-rules.store') }}" style="border-top:1px solid #e3e8ef;margin-top:1.5rem;padding-top:1rem">@csrf
<h3>Nuova regola</h3><div class="grid grid-2"><div><label>Nome</label><input name="name" required></div><div><label>Parole chiave separate da virgola</label><input name="keywords_text" required></div><div><label>Prezzo minimo</label><input type="number" step="0.01" name="minimum_price" required></div><div><label>Prezzo massimo</label><input type="number" step="0.01" name="maximum_price" required></div></div><label>Campi obbligatori del payload</label><textarea name="required_fields_text" rows="2"></textarea><div class="grid grid-2"><div><label>Include</label><textarea name="includes" rows="3"></textarea></div><div><label>Esclude</label><textarea name="excludes" rows="3"></textarea></div></div><label>Validità (giorni)</label><input type="number" name="validity_days" value="15" required><label style="font-weight:400"><input style="width:auto" type="checkbox" name="is_active" value="1" checked> Attiva</label><br><button class="btn">Aggiungi regola</button></form>
</section>
@endsection
