@extends('layouts.app')
@section('title', 'Azienda e AI · Daria')

@push('styles')
<style>
    .settings-stack{display:grid;gap:12px}.config-panel{padding:0;overflow:hidden}.config-panel>summary{list-style:none;display:flex;align-items:center;justify-content:space-between;gap:18px;padding:19px 22px;cursor:pointer}.config-panel>summary::-webkit-details-marker,.rule-editor>summary::-webkit-details-marker{display:none}.config-panel>summary:hover{background:#fafbfc}.config-panel[open]>summary{background:#fff9f4}.config-title{display:flex;align-items:flex-start;gap:13px;min-width:0}.config-number{flex:0 0 30px;width:30px;height:30px;border-radius:9px;background:var(--brand-soft);color:var(--brand-dark);display:grid;place-items:center;font-weight:800}.config-title h2{margin:0 0 3px;font-size:16px}.config-summary{color:var(--muted);font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:760px}.config-action{color:#475467;font-size:12px;font-weight:750;white-space:nowrap}.config-action:after{content:'⌄';display:inline-block;margin-left:8px;font-size:16px;transition:transform .16s}.config-panel[open]>summary .config-action:after{transform:rotate(180deg)}.config-body{padding:4px 22px 22px;border-top:1px solid var(--line)}.section-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:20px}.setting-checks{display:grid;gap:9px;margin:15px 0}.setting-check{display:flex;gap:10px;align-items:flex-start;padding:11px 12px;border:1px solid #eaecf0;border-radius:9px;background:#fafbfc}.setting-check input{width:auto;margin-top:3px}.setting-check label{margin:0;font-weight:650}.setting-check small{display:block;color:var(--muted);font-weight:400;margin-top:2px}.rule-list{display:grid;gap:8px}.rule-editor{border:1px solid #e4e7ec;border-radius:10px;background:white;overflow:hidden}.rule-editor>summary{list-style:none;display:grid;grid-template-columns:minmax(180px,1fr) minmax(150px,.7fr) auto auto;gap:12px;align-items:center;padding:13px 14px;cursor:pointer}.rule-editor>summary:hover{background:#fafbfc}.rule-editor[open]>summary{background:#f9fafb;border-bottom:1px solid #eaecf0}.rule-name{font-weight:750;color:#101828}.rule-meta{color:var(--muted);font-size:12px}.rule-body{padding:4px 15px 17px}.empty-state{padding:20px;text-align:center;border:1px dashed #d0d5dd;border-radius:10px;color:var(--muted)}.provider-strip{padding:14px 18px;margin-bottom:16px}.overview-badges{display:flex;gap:7px;flex-wrap:wrap;margin-top:8px}@media(max-width:760px){.config-panel>summary{padding:16px}.config-body{padding:3px 16px 18px}.config-action{font-size:0}.config-action:after{font-size:18px}.rule-editor>summary{grid-template-columns:1fr auto}.rule-editor>summary .rule-meta:nth-child(2){display:none}.section-actions .btn{width:100%}}
</style>
@endpush

@section('content')
<div class="toolbar">
    <div><div class="page-kicker">Configurazione</div><h1>Azienda e AI</h1><p class="muted">Modifica solo la sezione che ti serve. Completezza del profilo: <strong>{{ $settings->completeness ?? 0 }}%</strong>.</p></div>
    <a class="btn" href="{{ route('setup-wizard.create') }}">Compila con Daria</a>
</div>

<div class="card provider-strip"><div class="toolbar" style="margin:0"><div><strong>Motore AI {{ strtoupper($aiStatus['provider']) }}</strong><div class="muted">Modello {{ $aiStatus['model'] }} · configurazione globale protetta</div></div><span class="badge {{ $aiStatus['configured'] ? 'success' : 'hot' }}">{{ $aiStatus['configured'] ? 'Operativo' : 'Chiave mancante' }}</span></div>@unless($aiStatus['configured'])<div class="error">Imposta <code>OPENAI_API_KEY</code> nel file <code>.env</code> del server.</div>@endunless</div>

<div class="settings-stack">
    <details class="card config-panel" @if($errors->any() && old('section') === 'identity') open @endif>
        <summary><div class="config-title"><span class="config-number">1</span><div><h2>Identità aziendale</h2><div class="config-summary">{{ $settings->commercial_name ?: 'Nome non impostato' }} · {{ $settings->industry ?: 'settore non impostato' }}@if($settings->service_area) · {{ $settings->service_area }}@endif</div></div></div><span class="config-action">Modifica</span></summary>
        <div class="config-body"><form method="post" action="{{ route('settings.organization.update') }}">@csrf @method('put')<input type="hidden" name="section" value="identity">
            <div class="grid grid-2"><div><label>Ragione sociale</label><input name="legal_name" value="{{ old('legal_name',$settings->legal_name) }}"></div><div><label>Nome commerciale *</label><input name="commercial_name" value="{{ old('commercial_name',$settings->commercial_name) }}" required></div><div><label>Sito aziendale</label><input type="url" name="website_url" value="{{ old('website_url',$settings->website_url) }}" placeholder="https://www.azienda.it"></div><div><label>Settore *</label><input name="industry" value="{{ old('industry',$settings->industry) }}" required></div><div><label>Area geografica servita</label><input name="service_area" value="{{ old('service_area',$settings->service_area) }}"></div></div>
            @if($errors->any() && old('section') === 'identity') @foreach($errors->all() as $error)<div class="error">{{ $error }}</div>@endforeach @endif<div class="section-actions"><button class="btn">Salva identità</button></div>
        </form></div>
    </details>

    <details class="card config-panel" @if($errors->any() && old('section') === 'offering') open @endif>
        <summary><div class="config-title"><span class="config-number">2</span><div><h2>Offerta commerciale</h2><div class="config-summary">{{ \Illuminate\Support\Str::limit($settings->products_services ?: 'Prodotti e servizi non ancora descritti', 105) }}</div></div></div><span class="config-action">Modifica</span></summary>
        <div class="config-body"><form method="post" action="{{ route('settings.organization.update') }}">@csrf @method('put')<input type="hidden" name="section" value="offering">
            <label>Descrizione dell’attività *</label><textarea name="business_description" rows="4" required>{{ old('business_description',$settings->business_description) }}</textarea><label>Prodotti e servizi *</label><textarea name="products_services" rows="5" required>{{ old('products_services',$settings->products_services) }}</textarea><label>Cliente ideale *</label><textarea name="ideal_customer" rows="4" required>{{ old('ideal_customer',$settings->ideal_customer) }}</textarea>
            <div class="grid grid-2"><div><label>Indicazioni generali sui prezzi</label><textarea name="pricing_rules" rows="4">{{ old('pricing_rules',$settings->pricing_rules) }}</textarea></div><div><label>Elementi distintivi</label><textarea name="differentiators" rows="4">{{ old('differentiators',$settings->differentiators) }}</textarea></div></div>
            @if($errors->any() && old('section') === 'offering') @foreach($errors->all() as $error)<div class="error">{{ $error }}</div>@endforeach @endif<div class="section-actions"><button class="btn">Salva offerta</button></div>
        </form></div>
    </details>

    <details class="card config-panel" @if($errors->any() && old('section') === 'lead_handling') open @endif>
        <summary><div class="config-title"><span class="config-number">3</span><div><h2>Gestione delle richieste</h2><div class="config-summary">Tono: {{ $settings->tone_of_voice ?: 'non impostato' }} · {{ count($settings->qualification_questions ?? []) }} domande · risposta {{ $settings->promised_response_minutes ? 'entro '.$settings->promised_response_minutes.' min' : 'senza tempo promesso' }}</div></div></div><span class="config-action">Modifica</span></summary>
        <div class="config-body"><form method="post" action="{{ route('settings.organization.update') }}">@csrf @method('put')<input type="hidden" name="section" value="lead_handling">
            <div class="grid grid-2"><div><label>Domande di qualificazione, una per riga</label><textarea name="qualification_questions_text" rows="6">{{ old('qualification_questions_text',implode("\n",$settings->qualification_questions ?? [])) }}</textarea></div><div><label>Criteri di esclusione</label><textarea name="exclusion_criteria" rows="6">{{ old('exclusion_criteria',$settings->exclusion_criteria) }}</textarea></div><div><label>Tono di voce *</label><input name="tone_of_voice" value="{{ old('tone_of_voice',$settings->tone_of_voice ?: 'professionale e diretto') }}" required></div><div><label>Tempo di risposta promesso (minuti)</label><input type="number" min="1" name="promised_response_minutes" value="{{ old('promised_response_minutes',$settings->promised_response_minutes) }}"></div><div><label>Modalità appuntamento</label><input name="appointment_details" value="{{ old('appointment_details',$settings->appointment_details) }}"></div></div><label>Firma delle risposte *</label><textarea name="email_signature" rows="4" required>{{ old('email_signature',$settings->email_signature) }}</textarea>
            @if($errors->any() && old('section') === 'lead_handling') @foreach($errors->all() as $error)<div class="error">{{ $error }}</div>@endforeach @endif<div class="section-actions"><button class="btn">Salva gestione richieste</button></div>
        </form></div>
    </details>

    <details class="card config-panel" @if($errors->any() && old('section') === 'automation') open @endif>
        <summary><div class="config-title"><span class="config-number">4</span><div><h2>Automazioni</h2><div class="overview-badges"><span class="badge {{ $settings->auto_analyze_new_leads ? 'success' : '' }}">Analisi {{ $settings->auto_analyze_new_leads ? 'ON' : 'OFF' }}</span><span class="badge {{ $settings->auto_send_initial_email ? 'success' : '' }}">Prima email {{ $settings->auto_send_initial_email ? 'ON' : 'OFF' }}</span><span class="badge {{ $settings->conversation_automation_enabled ? 'success' : '' }}">Conversazioni {{ $settings->conversation_automation_enabled ? 'ON' : 'OFF' }}</span></div></div></div><span class="config-action">Modifica</span></summary>
        <div class="config-body"><form method="post" action="{{ route('settings.organization.update') }}">@csrf @method('put')<input type="hidden" name="section" value="automation">
            <div class="warning">L’invio automatico avviene soltanto quando tutti i controlli deterministici vengono superati.</div>@unless(config('commerciale-ai.automation.external_send_enabled'))<div class="notice">Il server è in modalità test: gli invii automatici sono consentiti soltanto ai destinatari interni elencati sotto.</div>@endunless
            <div class="setting-checks">
                <div class="setting-check"><input id="auto_analyze_new_leads" type="checkbox" name="auto_analyze_new_leads" value="1" @checked(old('auto_analyze_new_leads',$settings->auto_analyze_new_leads))><label for="auto_analyze_new_leads">Analizza automaticamente i nuovi lead<small>Avvia qualificazione e preparazione della prima risposta.</small></label></div>
                <div class="setting-check"><input id="auto_send_initial_email" type="checkbox" name="auto_send_initial_email" value="1" @checked(old('auto_send_initial_email',$settings->auto_send_initial_email))><label for="auto_send_initial_email">Invia automaticamente la prima email<small>Richiede analisi automatica e superamento dei controlli.</small></label></div>
                <div class="setting-check"><input id="conversation_automation_enabled" type="checkbox" name="conversation_automation_enabled" value="1" @checked(old('conversation_automation_enabled',$settings->conversation_automation_enabled))><label for="conversation_automation_enabled">Automatizza le risposte successive<small>Gestisce le risposte ricevute via IMAP fino ai limiti impostati.</small></label></div>
                <div class="setting-check"><input id="auto_send_quotes_enabled" type="checkbox" name="auto_send_quotes_enabled" value="1" @checked(old('auto_send_quotes_enabled',$settings->auto_send_quotes_enabled))><label for="auto_send_quotes_enabled">Consenti preventivi automatici affidabili<small>Opera soltanto sulle regole del listino strutturato.</small></label></div>
                <div class="setting-check"><input id="internal_test_only" type="checkbox" name="internal_test_only" value="1" @checked(old('internal_test_only',$settings->exists ? $settings->internal_test_only : true))><label for="internal_test_only">Limita ai test interni<small>Blocca ogni destinatario che non compare nella lista autorizzata.</small></label></div>
            </div>
            <div class="grid grid-2"><div><label>Destinatari interni autorizzati, uno per riga</label><textarea name="automation_allowed_recipients_text" rows="5">{{ old('automation_allowed_recipients_text',implode("\n",$settings->automation_allowed_recipients ?? [])) }}</textarea></div><div><label>Massimo risposte automatiche per lead</label><input type="number" min="1" max="10" name="max_automatic_replies" value="{{ old('max_automatic_replies',$settings->max_automatic_replies ?? 3) }}" required><label>Importo massimo automatico (€)</label><input type="number" min="0" step="0.01" name="max_auto_quote_amount" value="{{ old('max_auto_quote_amount',$settings->max_auto_quote_amount) }}"></div></div>
            @if($errors->any() && old('section') === 'automation') @foreach($errors->all() as $error)<div class="error">{{ $error }}</div>@endforeach @endif<div class="section-actions"><button class="btn">Salva automazioni</button></div>
        </form></div>
    </details>

    <details class="card config-panel" @if($errors->any() && old('section') === 'privacy') open @endif>
        <summary><div class="config-title"><span class="config-number">5</span><div><h2>Privacy e conservazione</h2><div class="config-summary">Lead chiusi conservati per {{ $settings->data_retention_days ?? 730 }} giorni · cancellazione automatica {{ $settings->privacy_cleanup_enabled ? 'attiva' : 'disattivata' }}</div></div></div><span class="config-action">Modifica</span></summary>
        <div class="config-body"><form method="post" action="{{ route('settings.organization.update') }}">@csrf @method('put')<input type="hidden" name="section" value="privacy"><p class="muted">La cancellazione automatica riguarda esclusivamente i lead chiusi e si applica solo quando viene abilitata.</p><div class="grid grid-2"><div><label>Conservazione lead chiusi (giorni)</label><input type="number" name="data_retention_days" min="30" max="3650" required value="{{ old('data_retention_days',$settings->data_retention_days ?? 730) }}"></div><div class="setting-check" style="margin-top:15px"><input id="privacy_cleanup_enabled" type="checkbox" name="privacy_cleanup_enabled" value="1" @checked(old('privacy_cleanup_enabled',$settings->privacy_cleanup_enabled))><label for="privacy_cleanup_enabled">Cancellazione automatica alla scadenza</label></div></div>
            @if($errors->any() && old('section') === 'privacy') @foreach($errors->all() as $error)<div class="error">{{ $error }}</div>@endforeach @endif<div class="section-actions"><a class="btn btn-muted" href="{{ route('account.data-export') }}">Esporta dati</a><button class="btn">Salva privacy</button></div>
        </form></div>
    </details>

    <details class="card config-panel" @if(str_starts_with((string) old('_editor'), 'pricing')) open @endif>
        <summary><div class="config-title"><span class="config-number">6</span><div><h2>Listino strutturato</h2><div class="config-summary">{{ $pricingRules->count() }} {{ $pricingRules->count() === 1 ? 'regola' : 'regole' }} · {{ $pricingRules->where('is_active',true)->count() }} attive. I prezzi comunicati da Daria provengono da qui.</div></div></div><span class="config-action">Gestisci</span></summary>
        <div class="config-body">
            @if($pricingRules->isEmpty())<div class="empty-state">Non hai ancora creato fasce di prezzo strutturate.</div>@endif
            <div class="rule-list">
                @foreach($pricingRules as $rule)
                <details class="rule-editor" @if(old('_editor') === 'pricing-'.$rule->id) open @endif>
                    <summary><span class="rule-name">{{ $rule->name }}</span><span class="rule-meta">€ {{ number_format($rule->minimum_price,0,',','.') }}–{{ number_format($rule->maximum_price,0,',','.') }}</span><span class="badge {{ $rule->is_active ? 'success' : '' }}">{{ $rule->is_active ? 'Attiva' : 'In pausa' }}</span><span class="config-action">Modifica</span></summary>
                    <div class="rule-body"><form method="post" action="{{ route('settings.pricing-rules.update',$rule) }}">@csrf @method('put')<input type="hidden" name="_editor" value="pricing-{{ $rule->id }}">
                        <div class="grid grid-2"><div><label>Nome</label><input name="name" value="{{ old('_editor') === 'pricing-'.$rule->id ? old('name') : $rule->name }}" required></div><div><label>Parole chiave, separate da virgola</label><input name="keywords_text" value="{{ old('_editor') === 'pricing-'.$rule->id ? old('keywords_text') : implode(', ',$rule->keywords) }}" required></div><div><label>Prezzo minimo</label><input type="number" step="0.01" name="minimum_price" value="{{ old('_editor') === 'pricing-'.$rule->id ? old('minimum_price') : $rule->minimum_price }}" required></div><div><label>Prezzo massimo</label><input type="number" step="0.01" name="maximum_price" value="{{ old('_editor') === 'pricing-'.$rule->id ? old('maximum_price') : $rule->maximum_price }}" required></div></div>
                        <label>Campi obbligatori del payload, uno per riga</label><textarea name="required_fields_text" rows="2">{{ old('_editor') === 'pricing-'.$rule->id ? old('required_fields_text') : implode("\n",$rule->required_fields ?? []) }}</textarea><div class="grid grid-2"><div><label>Include</label><textarea name="includes" rows="3">{{ old('_editor') === 'pricing-'.$rule->id ? old('includes') : $rule->includes }}</textarea></div><div><label>Esclude</label><textarea name="excludes" rows="3">{{ old('_editor') === 'pricing-'.$rule->id ? old('excludes') : $rule->excludes }}</textarea></div></div>
                        <div class="grid grid-2"><div><label>Validità (giorni)</label><input type="number" name="validity_days" value="{{ old('_editor') === 'pricing-'.$rule->id ? old('validity_days') : $rule->validity_days }}" required></div><div class="setting-check" style="margin-top:15px"><input id="rule-active-{{ $rule->id }}" type="checkbox" name="is_active" value="1" @checked(old('_editor') === 'pricing-'.$rule->id ? old('is_active') : $rule->is_active)><label for="rule-active-{{ $rule->id }}">Regola attiva</label></div></div>
                        @if($errors->any() && old('_editor') === 'pricing-'.$rule->id) @foreach($errors->all() as $error)<div class="error">{{ $error }}</div>@endforeach @endif<div class="section-actions"><button class="btn">Salva regola</button></div>
                    </form></div>
                </details>
                @endforeach

                <details class="rule-editor" @if(old('_editor') === 'pricing-new') open @endif>
                    <summary><span class="rule-name">＋ Nuova regola di prezzo</span><span class="rule-meta">Aggiungi una fascia deterministica</span><span></span><span class="config-action">Apri</span></summary>
                    <div class="rule-body"><form method="post" action="{{ route('settings.pricing-rules.store') }}">@csrf<input type="hidden" name="_editor" value="pricing-new">
                        <div class="grid grid-2"><div><label>Nome</label><input name="name" value="{{ old('_editor') === 'pricing-new' ? old('name') : '' }}" required></div><div><label>Parole chiave, separate da virgola</label><input name="keywords_text" value="{{ old('_editor') === 'pricing-new' ? old('keywords_text') : '' }}" required></div><div><label>Prezzo minimo</label><input type="number" step="0.01" name="minimum_price" value="{{ old('_editor') === 'pricing-new' ? old('minimum_price') : '' }}" required></div><div><label>Prezzo massimo</label><input type="number" step="0.01" name="maximum_price" value="{{ old('_editor') === 'pricing-new' ? old('maximum_price') : '' }}" required></div></div>
                        <label>Campi obbligatori del payload, uno per riga</label><textarea name="required_fields_text" rows="2">{{ old('_editor') === 'pricing-new' ? old('required_fields_text') : '' }}</textarea><div class="grid grid-2"><div><label>Include</label><textarea name="includes" rows="3">{{ old('_editor') === 'pricing-new' ? old('includes') : '' }}</textarea></div><div><label>Esclude</label><textarea name="excludes" rows="3">{{ old('_editor') === 'pricing-new' ? old('excludes') : '' }}</textarea></div></div>
                        <div class="grid grid-2"><div><label>Validità (giorni)</label><input type="number" name="validity_days" value="{{ old('_editor') === 'pricing-new' ? old('validity_days',15) : 15 }}" required></div><div class="setting-check" style="margin-top:15px"><input id="new-rule-active" type="checkbox" name="is_active" value="1" checked><label for="new-rule-active">Regola attiva</label></div></div>
                        @if($errors->any() && old('_editor') === 'pricing-new') @foreach($errors->all() as $error)<div class="error">{{ $error }}</div>@endforeach @endif<div class="section-actions"><button class="btn">Aggiungi regola</button></div>
                    </form></div>
                </details>
            </div>
        </div>
    </details>
</div>
@endsection
